# Generated by Django 5.0.6 on 2024-06-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"verbose_name": "borrowing", "verbose_name_plural": "borrowings"},
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
