# Generated by Django 5.0.6 on 2024-06-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing_app", "0002_alter_borrowing_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="users",
            new_name="user",
        ),
    ]
