# Generated by Django 5.0.6 on 2024-06-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.PositiveIntegerField(),
        ),
    ]
