# Generated by Django 5.0.6 on 2024-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books_app", "0002_alter_book_daily_fee_alter_book_inventory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.PositiveIntegerField(),
        ),
    ]
