# Generated by Django 5.0.6 on 2024-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books_app", "0003_alter_book_daily_fee_alter_book_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.IntegerField(),
        ),
    ]
