# Generated by Django 5.0.6 on 2024-06-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
