# Generated by Django 5.0.6 on 2024-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_app", "0002_alter_payment_session_id_alter_payment_session_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
